### ISSUE TITLE
mode method error with single value arrays

### ISSUE THREAD

**Issue by apokalipto** [mgrigajtis/easystats#12]
``` ruby
[0,0,0].mode
NoMethodError: undefined method `[]' for nil:NilClass
easystats-0.5.0/lib/easystats.rb:46:in `mode'
```

The following is wrong.

``` ruby
return if frequencies[-1][1] == frequencies[-2][1]
```

For single value arrays like [0,0,0] the sorted frequencies is [[0,3]] for which the [[0,3]][-2] is nil.

Maybe the solution is to return the array's first element when

``` ruby
uniq.count.eql?(1)
```

 is true.

**Comment by mgrigajtis** [comment]
It's been a long time since I touched this project.  I'll need to dust it off at some point.

**Comment by mgrigajtis** [comment]
I have updated the mode function.
