### ISSUE TITLE
broken link and question

### ISSUE THREAD

**Issue by brettskiii** [mgrigajtis/easystats#9]
Created by Matthew Grigajtis ..

this link is broken..

what is the state of this gem, still used / active? Looks great, any ideas on how to sort the array like a histogram with the mean / mode etc in middle?

**Comment by mgrigajtis** [comment]
What link?

**Comment by brettskiii** [comment]
on the readme to creators website

**Comment by mgrigajtis** [comment]
Gem is still used very widely, haven't had to make any changes recently.  What link are you talking about?

**Comment by mgrigajtis** [comment]
Oh that...  I let that domain expire, I wasn't using it.  I guess I should remove it from the README.

**Comment by brettskiii** [comment]
no biggie, great gem thank you :)

**Comment by mgrigajtis** [comment]
You're very welcome!
